-- PASO 1: CREAR TABLA SI NO EXISTE
CREATE TABLE IF NOT EXISTS public.restaurante_menu (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    name TEXT NOT NULL,
    category TEXT NOT NULL,
    price DECIMAL(10,2) NOT NULL,
    description TEXT,
    available BOOLEAN DEFAULT true
);

-- PASO 2: HABILITAR RLS (Seguridad)
ALTER TABLE public.restaurante_menu ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Lectura pública restaurante" ON public.restaurante_menu FOR SELECT USING (true);
CREATE POLICY "Admin total restaurante" ON public.restaurante_menu FOR ALL USING (auth.role() = 'authenticated');

-- PASO 3: INSERTAR PLATOS
INSERT INTO public.restaurante_menu (name, category, price, description) VALUES
('CHAUFA REGIONAL', 'Platos Típicos', 25.00, 'Arroz chaufa elaborado con cecina y chorizo servido con plátano frito.'),
('TACACHO CON CECINA', 'Platos Típicos', 25.00, 'Tacacho con cecina + patacones + plátano frito + zarza de cebolla.'),
('JUANE SELVÁTICO', 'Platos Típicos', 25.00, 'Tacacho + juane selvático + zarza de cebolla.'),
('PATACONES RELLENOS', 'Platos Típicos', 25.00, 'Patacón relleno con ceviche de cecina regional.'),
('CHICHARRON DE CERDO', 'Platos Típicos', 30.00, 'Chicharrón de cerdo + Tacacho + patacones + plátano frito + zarza de cebolla.'),
('SUDADO DE TILAPIA', 'Pescados', 30.00, 'Arroz + sudado de tilapia + patacones.'),
('PATARASHCA DE TILAPIA', 'Pescados', 30.00, 'Arroz + patarashca de tilapia + patacones + maduro frito.'),
('TILAPIA FRITA/PARRILLA/PLANCHA', 'Pescados', 30.00, 'Arroz + patacones + tilapia + zarza de cebolla.'),
('TRUCHA FRITA/PARRILLA/PLANCHA', 'Pescados', 35.00, 'Arroz + patacones + trucha + zarza de cebolla.'),
('SUDADO DE TRUCHA', 'Pescados', 35.00, 'Arroz + sudado de trucha + patacones.'),
('PATARASHCA DE TRUCHA', 'Pescados', 35.00, 'Arroz + patarashca de trucha + patacones + maduro frito.'),
('POLLO FRITO/PLANCHA/PARRILLA', 'Pollos', 22.00, 'Pollo + plátano frito + papa frita + ensalada.'),
('CHICHARRON DE POLLO', 'Pollos', 22.00, 'Chicharrón de pollo + plátano frito + papa frita + ensalada.'),
('MILANESA DE POLLO', 'Pollos', 22.00, 'Pollo + plátano frito + papa frita + ensalada.'),
('PAICHE EN SALSA AMAZÓNICA', 'Paiches', 45.00, 'Preparado a la parrilla, mariscos en salsa de huacatay + yuca frita.'),
('PAICHE A LA PARRILLA', 'Paiches', 40.00, 'Arroz + paiche a la parrilla + patacones + yuca frita + zarza de cebolla.'),
('PAICHE A LA PLANCHA', 'Paiches', 40.00, 'Arroz + paiche a la plancha + patacones + yuca frita + zarza de cebolla.'),
('PATARASHCA DE PAICHE', 'Paiches', 40.00, 'Arroz + patarashca de paiche + patacón + plátano frito.'),
('CHICHARRON DE PAICHE', 'Paiches', 40.00, 'Arroz + chicharrón de paiche + patacón + plátano frito.'),
('CEVICHE DE TOYO', 'Ceviches', 30.00, 'Refrescante ceviche de toyo.'),
('CEVICHE MIXTO', 'Ceviches', 40.00, 'Ceviche con variedad de pescados y mariscos.'),
('CEVICHE DE PAICHE', 'Ceviches', 40.00, 'Ceviche premium de paiche amazónico.'),
('TRIO DE CEVICHE SELVÁTICO', 'Ceviches', 65.00, 'Toyo + Paiche + Cecina.'),
('CHANCHO A LA CAJA CHINA', 'Cerdo', 30.00, 'Cerdo crocante preparado en caja china.'),
('COSTILLAS EN SALSA BBQ', 'Cerdo', 28.00, 'Costillas de cerdo bañadas en salsa BBQ.'),
('CHORIZO CON TACACHO', 'Cerdo', 25.00, 'Chorizo regional acompañado de tacacho.'),
('MIXTO (Cecina + chorizo)', 'Cerdo', 30.00, 'Cecina y chorizo regional.'),
('COSTILLA AHUMADA EN SALSA DE COCONA', 'Cerdo', 30.00, 'Costilla con el toque cítrico de la cocona.'),
('CHULETA FRITA/PLANCHA/PARRILLA', 'Cerdo', 25.00, 'Chuleta de cerdo preparada al gusto.'),
('RONDA AMAZÓNICA (2 Pers)', 'Especiales', 79.00, 'JUANE AVISPA + CECINA + CHORIZO + CHAUFA REGIONAL.'),
('LA BUCHIZAPA (3 Pers)', 'Especiales', 99.00, 'JUANE AVISPA + CEVICHE DE PAICHE + CHICHARRON DE PAICHE + CHAUFA REGIONAL + CORONA.'),
('MAJADO EXÓTICO', 'Especiales', 45.00, 'MAJADO DE YUCA + MAJADO DE PLÁTANO + COSTILLAS AHUMADAS DE CASA + AJÍ DE COCONA.'),
('CREPS VEGETARIANO', 'Especiales', 29.00, 'Crepe enrollada con verdura salteada y bañada en salsa de pitajaya.'),
('CALDO DE GALLINA', 'Extras', 22.00, 'Sustancioso caldo de gallina regional.'),
('SOPA DIETA', 'Extras', 15.00, 'Sopa ligera y nutritiva.'),
('JUANE DE GALLINA', 'Extras', 25.00, 'Plato tradicional de arroz con gallina envuelto en hojas de bijao.'),
('ENSALADA DE FILETE', 'Extras', 15.00, 'Ensalada fresca con filete.'),
('TORTILLAS DE VERDURA', 'Extras', 15.00, 'Tortillas saludables con verduras frescas.'),
('ARROZ', 'Guarniciones', 5.00, 'Porción de arroz blanco.'),
('PAPA SANCOCHADA / FRITA', 'Guarniciones', 5.00, 'Papa al gusto.'),
('PATACONES', 'Guarniciones', 5.00, 'Porción de patacones crocantes.'),
('TACACHO', 'Guarniciones', 5.00, 'Porción de tacacho tradicional.'),
('YUCA SANCOCHADA / FRITA', 'Guarniciones', 5.00, 'Yuca al gusto.'),
('PLATANO FRITO', 'Guarniciones', 5.00, 'Porción de plátano frito.'),
('ZARZA CRIOLLA', 'Guarniciones', 5.00, 'Zarza de cebolla fresca.'),
('COCONA', 'Bebidas', 15.00, 'Jarra de refresco de cocona.'),
('CEBADA', 'Bebidas', 12.00, 'Jarra de refresco de cebada.'),
('MARACUYA', 'Bebidas', 15.00, 'Jarra de refresco de maracuya.'),
('CARAMBOLA', 'Bebidas', 12.00, 'Jarra de refresco de carambola.'),
('MAÍZ MORADO', 'Bebidas', 15.00, 'Jarra de chicha morada.'),
('TÉ / INFUSIONES', 'Bebidas Calientes', 6.00, 'Manzanilla, Hierba Luisa o Canela.'),
('CAFÉ A LA OLLA', 'Bebidas Calientes', 8.00, 'Café tradicional preparado a la olla.'),
('CAFÉ CON LECHE', 'Bebidas Calientes', 10.00, 'Café con leche regional.'),
('CHOCOLATE REGIONAL', 'Bebidas Calientes', 10.00, 'Chocolate pura pasta de cacao.'),
('CHOCOLATE CON LECHE', 'Bebidas Calientes', 12.00, 'Chocolate regional con leche.'),
('RONDA SELVÁTICA (6 Sabores)', 'Bebidas Regionales', 39.00, 'Degustación de 6 macerados típicos.'),
('CERVEZA ARTESANAL', 'Bebidas Regionales', 16.00, 'Cerveza artesanal de la casa (Chop o Botella).');
